import axios from 'axios';
const api = axios.create({ baseURL: '/api', timeout: 30000 });
export const getEvents = (params?: any) => api.get('/events', { params }).then(r => r.data);
export const getThreats = (params?: any) => api.get('/threats', { params }).then(r => r.data);
export const getPolicies = () => api.get('/policies').then(r => r.data);
export const updatePolicy = (id: number, data: any) => api.put(`/policies/${id}`, data).then(r => r.data);
export const getApprovals = () => api.get('/approvals').then(r => r.data);
export const approveAction = (id: number) => api.post(`/approvals/${id}/approve`).then(r => r.data);
export const denyAction = (id: number) => api.post(`/approvals/${id}/deny`).then(r => r.data);
export const sendAgentMessage = (body: any) => api.post('/agent/message', body).then(r => r.data);
export const runMockScenario = (scenario: string, userMessage?: string) => api.post(`/agent/mock?scenario=${scenario}`, { user_message: userMessage || scenario }).then(r => r.data);
export const getGatewayHealth = () => api.get('/gateway/health').then(r => r.data);
export const getStatus = () => api.get('/status').then(r => r.data);
